Feature/61/demo
ebu/benchmarkstt pull request #62
Opened 2019-05-08 12:51 UTC by EyalLavi

Adds a walk-through demo of v1.

2019-05-08 13:06 UTC, EyalLavi commented
To build the documentation you may have to `pip install -r docs/requirements.txt` before running `make docs`.

2019-06-25 12:35 UTC, EyalLavi commented
Add a REALLY simple tutorial without Regex

2019-06-28 15:06 UTC, danielthepope submitted a review, later dismissed
Well written! The version of `benchmarkstt` in these examples is out of date now, so I've added comments where the command needs to be changed.

2019-06-28 15:06 UTC, danielthepope commented on docs/DEMO.rst
> +* `Transcript generated by Kaldi <https://github.com/ebu/benchmarkstt/resources/demos/qt_kaldi.json>`_
I think these links are wrong. Ideally this should be a relative link so that it doesn't matter where the documentation is hosted e.g. readthedocs.io or ebu.github.io.

You should probably move the `demos` folder to `docs/_static`, so you can then link them like this
```
* `Subtitle file <_static/demos/qt_subs.xml>`_
```

That way seems to work for me, I don't know if there's a more preferred method to do this.

2019-06-28 15:06 UTC, danielthepope commented on docs/DEMO.rst
> +  benchmarkstt normalization -i qt_subs.xml -o qt_reference.txt --regexreplace "<[^>]+>" " "
This is an old-style command. We're now using `benchmarkstt-tools` for this sort of normalisation.
```suggestion
  benchmarkstt-tools normalization -i qt_subs.xml -o qt_reference.txt --regex "<[^>]+>" " "
```

2019-06-28 15:06 UTC, danielthepope commented on docs/DEMO.rst
> +We used the normalization rule :code:`--regexreplace` that takes two parameters: a regular expression pattern and the replacement string. In this case all XML tags will be replaced with a space. This
```suggestion
We used the normalization rule :code:`--regex` that takes two parameters: a regular expression pattern and the replacement string. In this case all XML tags will be replaced with a space. This will result in a lot of space characters, but these are ignored by the diff algorithm so we don't have to clean then up.
```

2019-06-28 15:06 UTC, danielthepope commented on docs/DEMO.rst
> +  benchmarkstt metrics --reference qt_reference.txt --hypothesis qt_aws_hypothesis.txt --wer --diffcounts
I'm not going to comment on every one of these examples, but again, this needs to be `benchmarkstt-tools`.

2019-06-28 15:06 UTC, danielthepope commented on docs/DEMO.rst
> +  benchmarkstt normalization -i qt_reference.txt -o qt_reference_normalized.txt --lowercase --regexreplace "[,.-]" " "
With these examples we can show how `benchmarkstt` can be used to normalise and gather metrics at the same time, instead of doing two separate steps.

2019-06-28 15:06 UTC, danielthepope commented on docs/DEMO.rst
> +You can see that a lot of the differences are due to capitalization and punctuation. We are only interested in the correct identification of words, so we these types of differences should not count a
```suggestion
You can see that a lot of the differences are due to capitalization and punctuation. We are only interested in the correct identification of words, so these types of differences should not count as errors. To get a more accurate WER, we will remove punctuation and convert all letters to lowercase. We will do this for the reference and both hypothesis files by using the :code:`normalize` subcommand again, with two rules: the built-in :code:`--lowercase` shortcut rule and the :code:`--regexreplace` rule:
```

2019-06-28 15:06 UTC, danielthepope commented on docs/DEMO.rst
> +For this demo, two machine transcripts were retrieved for the Question Time audio: from AWS Transcribe and from the BBC's version of Kaldi, an open-source STT framework. This version was trained on B
> This version was trained on BBC content so is expected to perform better.

Is that a necessary sentence?

2019-07-02 12:35 UTC, EyalLavi commented
Made the changes requested by @danielthepope, thanks!

Code samples use the named arguments `-r` and `-h`so I'll wait for #75 to merge.

2019-07-10 11:03 UTC, MikeSmithEU commented
@EyalLavi Request: rename directory BDD to bdd, to avoid issues with case sensitive file systems, just cleaner to have everything lowercase...

2019-07-10 11:06 UTC, MikeSmithEU commented
@EyalLavi Could you also check all mentions of `benchmarkstt`, as we split this up to `benchmarkstt-tools` for normalization, metrics, etc.

2019-07-11 15:40 UTC, MikeSmithEU requested changes

2019-07-11 15:40 UTC, MikeSmithEU commented on .gitignore
> +tests/BDD/features/normalization_file_handling.feature
shouldn't be here?

2019-08-14 12:54 UTC, MikeSmithEU approved these changes

2019-08-14 13:08 UTC, MikeSmithEU commented
Did complete re-read and execution of the demo and fixed some commands + added output.

Also did some further sphinx documentation cleanup:
 - Added restructuredtext diff formatter dialect (used so I could copy results directly in documentation, instead of having to use screenshots)
 - Added css for terminal output block and insertions/deletions for `--worddiffs`
 - Cleanup of all `.. code-block::`'s to use more readable `::` notation
 - Cleanup of all inline `:code:` to more readable `` notation
 - Bumped VERSION
 - Removed the param types from `:param param_name:` tags (was incorrect ReST syntax, use type hints instead)
 - Disable smartquotes in sphinx (preventing `--` to be converted to emdashes)
 - Set default highlight language to 'none' in sphinx
 - Proper use of `html_css_files` for additional css files
 - Improve markdown and rst output for OpcodeCounts (more readable)
 - Fixes in `.readthedocs.yml`

2019-08-14 13:24 UTC, MikeSmithEU approved these changes

2019-08-14 13:28 UTC, MikeSmithEU approved these changes

2019-08-14 13:29 UTC, MikeSmithEU approved these changes

2019-08-14 13:38 UTC, merged